// sidebarsBlinks.ts
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Getting Started",
    },
    {
      type: "doc",
      id: "quick-start",
      label: "Quick Start",
    },
    {
      type: "doc",
      id: "faq",
      label: "FAQ",
    },
    {
      type: "html",
      value: "SETUP YOUR APP",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "setup/register-app",
      label: "Registration",
    },
    {
      type: "doc",
      id: "setup/topics-channels-subscribers",
      label: "Topics, Channels & Subscribers",
    },
    {
      type: "doc",
      id: "setup/dashboard-introduction",
      label: "Dashboard Introduction",
    },
    {
      type: "html",
      value: "INTEGRATE AN INBOX",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "integrate-inbox/index",
      label: "Introduction",
    },
    {
      type: "doc",
      id: "integrate-inbox/user-management",
      label: "User Management",
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "doc",
        id: "integrate-inbox/api/index",
      },
      items: [
        {
          type: "doc",
          id: "integrate-inbox/api/authentication",
          label: "Authentication",
        },
        {
          type: "doc",
          id: "integrate-inbox/api/notifications",
          label: "Notifications",
        },
        {
          type: "doc",
          id: "integrate-inbox/api/push-notifications",
          label: "Push Notifications",
        },

      ],
    },
    {
      type: "category",
      label: "SDK",
      link: {
        type: "doc",
        id: "integrate-inbox/sdk/index",
      },
      items: [
        {
          type: "doc",
          id: "integrate-inbox/sdk/setup-configuration",
          label: "Setup & Configuration",
        },
        {
          type: "doc",
          id: "integrate-inbox/sdk/notifications-button",
          label: "NotificationsButton",
        },
        {
          type: "doc",
          id: "integrate-inbox/sdk/notifications",
          label: "Notifications",
        },
      ],
    },
    // {
    //   type: "doc",
    //   id: "integrate-inbox/mobile",
    //   label: "Mobile Integration",
    // },
    {
      type: "doc",
      id: "integrate-inbox/unified-inbox",
      label: "Unified Inbox",
    },
    {
      type: "html",
      value: "SEND ALERTS",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "send/index",
      label: "Introduction",
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "doc",
        id: "send/api/index",
      },
      items: [
        {
          type: "doc",
          id: "send/api/authentication",
          label: "Authentication",
        },
        {
          type: "doc",
          id: "send/api/send-messages",
          label: "Send Messages",
        },
        {
          type: "doc",
          id: "send/api/push-notifications",
          label: "Push Notifications",
        },
      ],
    },
    {
      type: "category",
      label: "SDK",
      link: {
        type: "doc",
        id: "send/sdk/index",
      },
      items: [
        {
          type: "doc",
          id: "send/sdk/setup-configuration",
          label: "Setup & Configuration",
        },
        {
          type: "doc",
          id: "send/sdk/send-messages",
          label: "Send Messages",
        },
      ],
    },
    {
      type: "doc",
      id: "send/dashboard",
      label: "Dashboard",
    },
    {
      type: "html",
      value: "EVENT DETECTION & MONITORING",
      className: "sidebar-title",
    },
    {
      type: "autogenerated",
      dirName: "alerts-and-monitoring",
    },
    {
      type: "html",
      value: "MOBILE ALERTS STACK",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "mobile-alerts/index",
      label: "Introduction",
    },

  ]
};

export default sidebars;
