// sidebarsBlinks.ts
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "link",
      href: "https://sbl.dial.to",
      label: "🔥 Standard Blinks Library",
    },
  ],
};

export default sidebars;
