// sidebarsBlinks.ts
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Getting Started",
    },
    {
      type: "doc",
      id: "quick-start",
      label: "Quick Start",
    },
    {
      type: "doc",
      id: "faq",
      label: "FAQ",
    },
    {
      type: "html",
      value: "SETUP YOUR APP",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "setup/register-app",
      label: "Registration",
    },
    {
      type: "doc",
      id: "setup/topics-channels-subscribers",
      label: "Topics, Channels & Subscribers",
    },
    {
      type: "doc",
      id: "setup/dashboard-introduction",
      label: "Dashboard Introduction",
    },
    {
      type: "html",
      value: "SEND ALERTS",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "send/index",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Programmatic Alerts",
      link: {
        type: "doc",
        id: "send/programmatic/index",
      },
      items: [
        "send/programmatic/api",
        {
          type: "category",
          label: "SDK",
          link: {
            type: "doc",
            id: "send/programmatic/sdk/index",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "send/programmatic/sdk",
            },
          ],
        },
      ],
    },
    {
      type: "doc",
      id: "send/dashboard",
      label: "Dashboard Alerts",
    },
    {
      type: "category",
      label: "Monitoring and Event Detection",
      link: {
        type: "doc",
        id: "send/monitoring/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "send/monitoring",
        },
      ],
    },
    {
      type: "html",
      value: "RECEIVE ALERTS",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "receive/index",
      label: "Introduction",
    },
    {
      type: "doc",
      id: "receive/user-subscription",
      label: "User Subscription Management",
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "doc",
        id: "receive/api/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "receive/api",
        },
      ],
    },
    {
      type: "category",
      label: "SDK",
      link: {
        type: "doc",
        id: "receive/sdk/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "receive/sdk",
        },
      ],
    },
    {
      type: "doc",
      id: "receive/mobile",
      label: "Mobile Integration",
    },
    {
      type: "doc",
      id: "receive/unified-feed",
      label: "Unified Feed",
    },
    // {
    //   type: "html",
    //   value: "OLD STRUCT ALERTS", // TODO: remove this once new structure is implemented
    //   className: "sidebar-title",
    // },
    // {
    //   type: "autogenerated",
    //   dirName: ".",
    // },
  ],
};

export default sidebars;
