// sidebarsBlinks.ts
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Getting Started",
    },
    {
      type: "doc",
      id: "quick-start",
      label: "Quick Start",
    },
    {
      type: "doc",
      id: "faq",
      label: "FAQ",
    },
    {
      type: "html",
      value: "SETUP YOUR APP",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "setup/register-app",
      label: "Registration",
    },
    {
      type: "doc",
      id: "setup/topics-channels-subscribers",
      label: "Topics, Channels & Subscribers",
    },
    {
      type: "doc",
      id: "setup/dashboard-introduction",
      label: "Dashboard Introduction",
    },
    {
      type: "html",
      value: "INTEGRATE AN INBOX",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "integrate-inbox/index",
      label: "Introduction",
    },
    {
      type: "doc",
      id: "integrate-inbox/user-subscription",
      label: "User Subscription Management",
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "doc",
        id: "integrate-inbox/api/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "integrate-inbox/api",
        },
      ],
    },
    {
      type: "category",
      label: "SDK",
      link: {
        type: "doc",
        id: "integrate-inbox/sdk/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "integrate-inbox/sdk",
        },
      ],
    },
    {
      type: "doc",
      id: "integrate-inbox/mobile",
      label: "Mobile Integration",
    },
    {
      type: "doc",
      id: "integrate-inbox/inbox",
      label: "Inbox",
    },
    {
      type: "html",
      value: "SEND ALERTS",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "send/index",
      label: "Introduction",
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "doc",
        id: "send/api/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "send/api",
        },
      ],
    },
    {
      type: "category",
      label: "SDK",
      link: {
        type: "doc",
        id: "send/sdk/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "send/sdk",
        },
      ],
    },
    {
      type: "doc",
      id: "send/dashboard",
      label: "Dashboard",
    },
    {
      type: "html",
      value: "EVENT DETECTION & MONITORING",
      className: "sidebar-title",
    },
    {
      type: "autogenerated",
      dirName: "alerts-and-monitoring",
    },
    {
      type: "html",
      value: "MOBILE ALERTS STACK",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "mobile-alerts/index",
      label: "Introduction",
    },
    // {
    //   type: "html",
    //   value: "OLD STRUCT ALERTS", // TODO: remove this once new structure is implemented
    //   className: "sidebar-title",
    // },
    // {
    //   type: "autogenerated",
    //   dirName: ".",
    // },
  ],
};

export default sidebars;
