// sidebarsBlinks.ts
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Getting Started",
    },
    {
      type: "html",
      value: "CLIENT",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "blinks-client/index",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Integrate",
      link: {
        type: "doc",
        id: "blinks-client/integrate/index",
      },
      items: [
        "blinks-client/integrate/headless/index",
        {
          type: "category",
          label: "UI Components",
          link: {
            type: "doc",
            id: "blinks-client/integrate/ui-components/index",
          },
          items: [
            {
              type: "doc",
              id: "blinks-client/integrate/ui-components/blinks",
              label: "Blinks",
            },
            {
              type: "doc",
              id: "blinks-client/integrate/ui-components/miniblinks",
              label: "Miniblinks (Buttons)",
            },
            {
              type: "doc",
              id: "blinks-client/integrate/ui-components/styling",
              label: "Styling",
            },
          ],
        },
        "blinks-client/integrate/chrome/index",
      ],
    },
    {
      type: "category",
      label: "Manage",
      link: {
        type: "doc",
        id: "blinks-client/manage/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "blinks-client/manage",
        },
      ],
    },
    {
      type: "category",
      label: "Measure",
      link: {
        type: "doc",
        id: "blinks-client/measure/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "blinks-client/measure",
        },
      ],
    },
    {
      type: "html",
      value: "PROVIDER (API)",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "blinks-provider/index",
      label: "Introduction",
    },
    {
      type: "doc",
      id: "blinks-provider/build-your-first-blink",
      label: "Build your first Blink",
    },
    {
      type: "doc",
      id: "blinks-provider/fallbacks",
      label: "Fallbacks",
    },
    {
      type: "doc",
      id: "blinks-provider/blink-registry",
      label: "Blink Registry",
    },
    {
      type: "category",
      label: "Advanced",
      link: {
        type: "doc",
        id: "blinks-provider/advanced/index",
      },
      items: [
        {
          type: "doc",
          id: "blinks-provider/advanced/forms",
          label: "Forms",
        },
        {
          type: "doc",
          id: "blinks-provider/advanced/action-chaining",
          label: "Action Chaining",
        },
        {
          type: "doc",
          id: "blinks-provider/advanced/track-tx",
          label: "Transaction Tracking",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "Guides",
        description:
          "Learn how to build a Blinks Provider, an API that serves Blinks to your application.",
        slug: "/blinks-provider/guides",
      },
      items: ["blinks-provider/guides/guide1"],
    },
    {
      type: "html",
      value: "SCAFFOLDS",
      className: "sidebar-title",
    },
    {
      type: "autogenerated",
      dirName: "blinks-scaffolds",
    },
    {
      type: "html",
      value: "MOAR",
      className: "sidebar-title",
    },
    {
      type: "html",
      value: `
          <a href="https://solana.com/developers/guides/advanced/actions" class="sidebar-social-link">
            Solana Spec
          </a>
        `,
      className: "sidebar-social",
    },
    {
      type: "html",
      value: `
          <a href="https://terminal.dial.to" class="sidebar-social-link">
            Terminal
          </a>
        `,
      className: "sidebar-social",
    },

    {
      type: "html",
      value: `
          <a href="https://dial.to" class="sidebar-social-link">
            Dial.to
          </a>
        `,
      className: "sidebar-social",
    },
  ],
};

export default sidebars;
